/*  This file is automatically generated by utils/glue.sh,
 *  called from the configure script.  Do not edit by hand!
 */

#include "shntool.h"

extern format_module format_wav;
extern format_module format_aiff;
extern format_module format_shn;
extern format_module format_flac;
extern format_module format_ape;
extern format_module format_alac;
extern format_module format_tak;
extern format_module format_ofr;
extern format_module format_tta;
extern format_module format_als;
extern format_module format_wv;
extern format_module format_lpac;
extern format_module format_la;
extern format_module format_mkw;
extern format_module format_bonk;
extern format_module format_kxs;
extern format_module format_cust;
extern format_module format_term;
extern format_module format_null;

format_module *st_formats[] = {
  &format_wav,
  &format_aiff,
  &format_shn,
  &format_flac,
  &format_ape,
  &format_alac,
  &format_tak,
  &format_ofr,
  &format_tta,
  &format_als,
  &format_wv,
  &format_lpac,
  &format_la,
  &format_mkw,
  &format_bonk,
  &format_kxs,
  &format_cust,
  &format_term,
  &format_null,
  NULL
};
