/*  This file is automatically generated by utils/glue.sh,
 *  called from the configure script.  Do not edit by hand!
 */

#include "shntool.h"

extern mode_module mode_len;
extern mode_module mode_fix;
extern mode_module mode_hash;
extern mode_module mode_pad;
extern mode_module mode_join;
extern mode_module mode_split;
extern mode_module mode_cat;
extern mode_module mode_cmp;
extern mode_module mode_cue;
extern mode_module mode_conv;
extern mode_module mode_info;
extern mode_module mode_strip;
extern mode_module mode_gen;
extern mode_module mode_trim;

mode_module *st_modes[] = {
  &mode_len,
  &mode_fix,
  &mode_hash,
  &mode_pad,
  &mode_join,
  &mode_split,
  &mode_cat,
  &mode_cmp,
  &mode_cue,
  &mode_conv,
  &mode_info,
  &mode_strip,
  &mode_gen,
  &mode_trim,
  NULL
};
